name: dakoku

on:
  workflow_dispatch:

jobs:
  dakoku:
    name: dakoku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Run
        env:
          JOBCAN_EMAIL: ${{ secrets.JOBCAN_EMAIL }}
          JOBCAN_PASSWORD: ${{ secrets.JOBCAN_PASSWORD }}
        run: |
          echo $JOBCAN_EMAIL
          go run main.go
